# Generated by Django 2.1.1 on 2018-10-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=20)),
                ('food_category', models.CharField(max_length=20)),
                ('station', models.CharField(max_length=20)),
                ('langlat', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('operating_hours', models.CharField(blank=True, max_length=20)),
                ('search_num', models.IntegerField(default=0)),
                ('like_num', models.IntegerField(default=0)),
                ('review_num', models.IntegerField(default=0)),
            ],
        ),
    ]
