# Generated by Django 2.1.1 on 2018-10-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='food_category',
            new_name='foodCategory',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='like_num',
            new_name='likeNum',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='langlat',
            new_name='lnglat',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='operating_hours',
            new_name='operatingHours',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant_name',
            new_name='restaurantName',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='review_num',
            new_name='reviewNum',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='search_num',
            new_name='searchNum',
        ),
    ]
