# Generated by Django 2.1.1 on 2018-10-31 18:27

import dining.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0005_auto_20181101_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodimage',
            name='foodImage',
            field=models.ImageField(upload_to=dining.models.user_directory_path),
        ),
    ]
