# Generated by Django 2.1.1 on 2018-10-31 18:52

import dining.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0006_auto_20181101_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuImage', models.ImageField(upload_to=dining.models.menu_directory_path)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dining.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantImage', models.ImageField(upload_to=dining.models.restaurant_directory_path)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dining.Restaurant')),
            ],
        ),
        migrations.AlterField(
            model_name='foodimage',
            name='foodImage',
            field=models.ImageField(upload_to=dining.models.food_directory_path),
        ),
    ]
