# Generated by Django 2.1.1 on 2018-10-31 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0007_auto_20181101_0352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuimage',
            old_name='menu',
            new_name='restaurant',
        ),
    ]
