# Generated by Django 2.1.1 on 2018-11-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0008_auto_20181101_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='lnglat',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
