# Generated by Django 2.1.1 on 2018-11-06 20:32

import dining.media_directory
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0010_auto_20181101_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='representative_image',
            field=models.ImageField(blank=True, upload_to=dining.media_directory.representative_directory_path),
        ),
    ]
