# Generated by Django 2.1.1 on 2018-11-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0011_auto_20181107_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='foodImageList',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menuImageList',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurantImageList',
            field=models.TextField(blank=True),
        ),
    ]
